# : Manager [[[

[mgr]
cwd = { fg = "#ffffff" }

# Find
find_keyword = { fg = "#f38ba8", bold = true, italic = true, underline = true }
find_position = { fg = "#f38ba8", bold = true, italic = true }

# Marker
marker_copied = { fg = "#19806f", bg = "#19806f" }
marker_cut = { fg = "#19806f", bg = "#19806f" }
marker_marked = { fg = "#f38ba8", bg = "#f38ba8" }
marker_selected = { fg = "#94e2d5", bg = "#94e2d5" }

# Count
count_copied = { fg = "#ffffff", bg = "#19806f" }
count_cut = { fg = "#ffffff", bg = "#19806f" }
count_selected = { fg = "#e6e1e5", bg = "#94e2d5" }

# Border
border_style  = { fg = "#cba6f7" }

# : ]]]


# : Status [[[

[status]
overall = { fg = "#cba6f7" }
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#cba6f7", bg = "#1e1e2e" }
progress_error = { fg = "#f38ba8", bg = "#1e1e2e" }

# Permissions
perm_type = { fg = "#fab387" }
perm_write = { fg = "#94e2d5" }
perm_exec = { fg = "#f38ba8" }
perm_read = { fg = "#19806f" }
perm_sep = { fg = "#460594" }

# : ]]]


# : Mode [[[

[mode]

normal_main = { bg = "#cba6f7", fg = "#e6e1e5", bold = true }
normal_alt  = { bg = "#28283d", fg = "#ffffff" }

select_main = { bg = "#fab387", fg = "#000000", bold = true }
select_alt  = { bg = "#28283d", fg = "#ffffff" }

unset_main = { bg = "#94e2d5", fg = "#000000", bold = true }
unset_alt  = { bg = "#28283d", fg = "#ffffff" }

# : ]]]


# : Input [[[

[input]
border = { fg = "#cba6f7" }
title = {}
value = { fg = "#ffffff" }
selected = { reversed = true }

# : ]]]


# : Tabs [[[

[tabs]
active = { fg = "#cba6f7", bold = true, bg = "#1e1e2e" }
inactive = { fg = "#fab387", bg = "#1e1e2e" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#cba6f7", bg = "#e6e1e5" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#cba6f7" }
title = {}
hovered = { fg = "#19806f", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#1e1e2e" }
cand = { fg = "#cba6f7" }
rest = { fg = "#e6e1e5" }
desc = { fg = "#ffffff" }
separator = " ▶ "
separator_style = { fg = "#ffffff" }

# : ]]]

# : Spotter [[[

[spot]
border   = { fg = "#cba6f7" }
title    = { fg = "#cba6f7" }
tbl_col  = { fg = "#ffffff" }
tbl_cell = { fg = "#ffffff", bg = "#1e1e2e" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ffffff" }
run = { fg = "#ffffff" }
hovered = { reversed = true, bold = true }
footer = { fg = "#000000", bg = "#fab387" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#94e2d5" }
title_warn = { fg = "#cba6f7" }
title_error = { fg = "#f38ba8" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { mime = "*", is = "orphan", fg = "#ffffff", bg = "#92072e" },
    { mime = "application/*exec*", fg = "#f38ba8" },

    # Fallback
    { url = "*", fg = "#ffffff" },
    { url = "*/", fg = "#cba6f7" },
]

# : ]]]
